<table class="table-custom">
    <thead>
        <tr>
            <th>Code</th>
            <th>Status</th>
            <th>Generated By</th>
            <th>Used At</th>
            <th class="text-center align-middle">Actions</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($qrCodes as $qr)
            <tr>
                <td>{{ $qr->code }}</td>

                <td>
                    @if($qr->status === 'active')
                        <span class="badge-active">Active</span>
                    @elseif($qr->status === 'used')
                        <span class="badge-used">Used</span>
                    @else
                        <span class="badge-expired">Expired</span>
                    @endif
                </td>

                <td>{{ $qr->creator->name ?? 'Unknown' }}</td>

                <td>
                    {{ $qr->used_at ? $qr->used_at->format('M d, Y H:i') : '-' }}
                </td>

            <td class="text-center align-middle">
                <div class="action-icons">

                    {{-- Mark as Used --}}
                    <div class="icon-box">
                        @if($qr->isActive())
                            <form action="{{ route('qr_codes.markUsed', $qr->id) }}"
                                method="POST">
                                @csrf
                                <button type="submit" class="btn btn-sm btn-link text-success p-0">
                                    <i class="bi bi-check-circle fs-5"></i>
                                </button>
                            </form>
                        @endif
                    </div>

                    {{-- View --}}
                    <div class="icon-box">
                        <a href="{{ route('qr_codes.show', $qr->id) }}"
                        target="_blank"
                        class="btn btn-sm btn-link text-primary p-0">
                            <i class="bi bi-eye fs-5"></i>
                        </a>
                    </div>

                    {{-- Delete --}}
                    <div class="icon-box">
                        <button class="btn btn-sm btn-link text-danger delete-qr p-0"
                                data-url="{{ route('qr_codes.destroy', $qr->id) }}">
                            <i class="bi bi-trash fs-5"></i>
                        </button>
                    </div>
                </div>
            </td>





            </tr>
        @empty
            <tr>
                <td colspan="5" class="text-center">No QR codes found.</td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="pagination-wrapper">
    {{ $qrCodes->links() }}
</div>
