<table class="table-custom">
    <thead>
        <tr>
            <th>QR</th>
            <th>#</th>
            <th>Item Name</th>
            <th>Code</th>
            <th>QR Picture</th>
            <th>Status</th>
            <th>Used At</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>

    <tbody>
        @forelse ($qrCodes as $index => $qr)
            <tr>
                {{-- QR Column (Short preview) --}}
                <td>
                    <span class="badge-active">
                        {{ $qr->code }}
                    </span>
                </td>

                {{-- Number --}}
                <td>
                    {{ ($qrCodes->currentPage() - 1) * $qrCodes->perPage() + $index + 1 }}
                </td>

                {{-- Item Name --}}
                <td>
                    {{ $qr->item_name ?? 'N/A' }}
                </td>

                {{-- Code --}}
                <td>
                    {{ $qr->code }}
                </td>

                {{-- QR Picture --}}
                <td>
                    <img src="{{ route('qr_codes.show', $qr->id) }}"
                         width="70"
                         height="70"
                         alt="QR Code">
                </td>

                {{-- Status --}}
                <td>
                    @if($qr->status === 'active')
                        <span class="badge-active">Active</span>
                    @elseif($qr->status === 'used')
                        <span class="badge-used">Used</span>
                    @else
                        <span class="badge-expired">Expired</span>
                    @endif
                </td>

                {{-- Used At --}}
                <td>
                    {{ $qr->used_at ? $qr->used_at->format('M d, Y H:i') : '-' }}
                </td>

            <td class="text-center">
                <div class="actions-wrapper">

                    <div class="actions-icons">
                        {{-- Mark as Used --}}
                        @if($qr->isActive())
                        <form action="{{ route('qr_codes.markUsed', $qr->id) }}"
                            method="POST">
                            @csrf
                            <button type="submit" class="icon-btn success">
                                <i class="bi bi-check-circle"></i>
                            </button>
                        </form>
                        @endif

                        {{-- View --}}
                        <a href="{{ route('qr_codes.show', $qr->id) }}"
                        target="_blank"
                        class="icon-btn primary">
                            <i class="bi bi-eye"></i>
                        </a>

                        {{-- Delete --}}
                        <button class="icon-btn danger delete-qr"
                                data-url="{{ route('qr_codes.destroy', $qr->id) }}">
                            <i class="bi bi-trash"></i>
                        </button>
                    </div>

                    <div class="generated-text">
                        Generated by {{ $qr->creator->name ?? 'Unknown' }}
                    </div>

                </div>
            </td>
            </tr>

        @empty
            <tr>
                <td colspan="8" class="text-center">
                    No items found.
                </td>
            </tr>
        @endforelse
    </tbody>
</table>

<div class="pagination-wrapper">
    {{ $qrCodes->links() }}
</div>
